# Generated by Django 4.2.11 on 2024-03-10 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_inventario_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recibo', models.IntegerField()),
                ('producto', models.CharField(max_length=5)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('id_cliente', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('metodo_pago', models.CharField(max_length=100)),
                ('monto', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Inventario',
        ),
        migrations.AddField(
            model_name='producto',
            name='inventario',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
