# Generated by Django 4.2.11 on 2024-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_compra_recibo_delete_inventario_producto_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
