# Generated by Django 4.2.11 on 2024-03-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recibo_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
