# Generated by Django 4.2.11 on 2024-03-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_recibo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibo',
            name='num_productos',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
