# Generated by Django 4.2.11 on 2024-03-14 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_recibo_num_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
