# Generated by Django 4.2.11 on 2024-03-14 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_compra_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='id',
            new_name='producto_id',
        ),
    ]
