# Generated by Django 4.2.11 on 2024-03-15 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_producto_compra_producto_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='producto_id',
            new_name='id',
        ),
    ]
